"""Write SURVEY_SUMMARY.md from screening.csv, review_decisions.csv, duplicates.csv and ports/.

Counts per criterion outcome, and every flagged or stored item with its reason.
Static: port modules are parsed (ast), never imported or run.
"""
import ast
import csv
import math
import re
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def grid_of(path):
    tree = ast.parse(path.read_text(encoding='utf-8'))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(getattr(t, 'id', None) == 'GRID' for t in node.targets):
            return ast.literal_eval(node.value)
    return {}


def reason_head(why):
    return re.split(r'[:(]', why, 1)[0].strip()


def table(counter, head):
    out = [f'| {head} | Files |', '|---|---:|']
    out += [f'| {k} | {v} |' for k, v in counter.most_common()]
    out.append(f'| **Total** | **{sum(counter.values())}** |')
    return out


def main():
    rows = list(csv.DictReader(open(ROOT / 'screening.csv', encoding='utf-8')))
    decisions = {r['fmz_id']: r for r in csv.DictReader(open(ROOT / 'review_decisions.csv', encoding='utf-8'))}
    dups = list(csv.DictReader(open(ROOT / 'duplicates.csv', encoding='utf-8')))
    ports = sorted((ROOT / 'ports').glob('*/module.py'), key=lambda p: int(p.parent.name.split('_')[0]))
    byid = {r['fmz_id']: r for r in rows}

    final = Counter()
    for r in rows:
        d = decisions.get(r['fmz_id'])
        final[d['final_outcome'] if d else r['overall']] += 1

    L = ['# FMZ survey summary (branch `survey`)', '',
         'Generated by `survey_tools/summarize.py` from `screening.csv`, `review_decisions.csv`,',
         '`duplicates.csv` and `ports/`. Corpus: 5,806 FMZ strategy files on `master` (commit 7853bb2),',
         'each linking to its FMZ page (`https://www.fmz.com/strategy/<id>`). Sources read 2026-09-29.',
         'Nothing was backtested, run or ranked; FMZ performance claims were not used (criterion 7).', '',
         'Method, contract and interpretation rules: `SURVEY_README.md`. Status and next steps: `PROGRESS.md`.', '',
         '## Where every file stands now', '']
    L += table(final, 'Outcome')
    L += ['', '`PORT_CANDIDATE` = passed the static screen and is waiting to be read and ported.',
          '`REJECTED_ON_READING` = screen passed it, reading showed it fails (reasons below).', '',
          '## Counts per criterion outcome (static screen, `screening.csv`)', '']
    for c, title in (('c1', 'Criterion 1 (fits the next-open interface)'),
                     ('c2', 'Criterion 2 (generic, volatility-normalised)'),
                     ('c3', 'Criterion 3 (crypto-exchange-only features)')):
        L += [f'### {title}', ''] + table(Counter(r[c] for r in rows), 'Outcome') + ['']
        reasons = Counter()
        for r in rows:
            for part in r[c + '_why'].split(' | '):
                if part:
                    reasons[reason_head(part)] += 1
        L += ['Reasons (a file can have several):', ''] + table(reasons, 'Reason') + ['']
    L += ['### By language and overall screen outcome', '',
          '| Language | ' + ' | '.join(sorted({r['overall'] for r in rows})) + ' |',
          '|---|' + '---:|' * len({r['overall'] for r in rows})]
    langs = defaultdict(Counter)
    for r in rows:
        langs[r['lang']][r['overall']] += 1
    for lg, cnt in sorted(langs.items(), key=lambda kv: -sum(kv[1].values())):
        L.append(f'| {lg} | ' + ' | '.join(str(cnt[o]) for o in sorted({r["overall"] for r in rows})) + ' |')
    vol = sum(1 for r in rows if 'USES_VOLUME' in r['notes'])
    L += ['', f'Files whose signals use volume: {vol} (held while not otherwise excluded: '
          f"{sum(1 for r in rows if r['overall'] == 'HELD_NEEDS_VOLUME')}).", '',
          '### Criterion 6 (near-duplicates)', '',
          f'{len(dups)} groups; {sum(int(d["n_members"]) for d in dups)} files in groups; '
          f'{sum(int(d["n_members"]) - 1 for d in dups)} collapsed onto their representative. '
          'Every group, with its representative and collapsed ids, is in `duplicates.csv`; '
          f'{sum(1 for _ in open(ROOT / "possible_duplicates.csv", encoding="utf-8")) - 1} '
          'near-threshold pairs to check by hand are in `possible_duplicates.csv`.', '']

    L += ['## Ports (criteria 4 and 5)', '',
          'Each port folder holds `module.py`, `original_source.md` (verbatim), `original_sizing.txt`',
          '(verbatim sizing and money-management code, labelled with line numbers) and `PORT_NOTES.md`.', '',
          '| FMZ id | Folder | Language | Declared grid | Trials |', '|---:|---|---|---|---:|']
    total = 0
    for p in ports:
        g = grid_of(p)
        n = math.prod(len(v) for v in g.values()) if g else 0
        total += n
        fid = p.parent.name.split('_')[0]
        L.append(f"| {fid} | `ports/{p.parent.name}/` | {byid[fid]['lang']} | "
                 + ', '.join(f'{k} x{len(v)}' for k, v in g.items()) + f' | {n} |')
    L += [f'| | **{len(ports)} ports** | | | **{total}** |', '']

    L += ['## Rejected on reading', '', '| FMZ id | File | Criterion | Reason |', '|---:|---|---|---|']
    for d in decisions.values():
        if d['final_outcome'] == 'REJECTED_ON_READING':
            L.append(f"| {d['fmz_id']} | {d['file']} | {d['criterion']} | {d['reason']} |")

    flagged = [r for r in rows if r['overall'] == 'FLAGGED_CRYPTO_ONLY']
    L += ['', f'## Flagged and stored under criterion 3 ({len(flagged)} files)', '',
          'Each is copied verbatim to `flagged/<id>_<slug>/original_source.md` with a `REASON.md`; not ported.',
          '"Kind" says whether the file is a trading strategy/bot or a tool, library or monitor.', '',
          '| FMZ id | Name | Language | Kind | Reason (crypto-exchange-only features found) |',
          '|---:|---|---|---|---|']
    for r in sorted(flagged, key=lambda r: int(r['fmz_id'])):
        kind = 'tool' if r['c1'] == 'FAIL' and 'not a signal strategy' in r['c1_why'] else 'strategy'
        name = r['name'].replace('|', '/')
        L.append(f"| [{r['fmz_id']}]({r['detail_url']}) | {name} | {r['lang']} | {kind} | "
                 f"{r['c3_why'].replace(' | ', '; ')} |")
    (ROOT / 'SURVEY_SUMMARY.md').write_text('\n'.join(L) + '\n', encoding='utf-8')
    print('SURVEY_SUMMARY.md written;', dict(final))


if __name__ == '__main__':
    main()
